const pokemonList = [
  {
    name: 'arcanine',
    img: 'Arcanine.png',
    element: 'fire',
    weigth: '20kg',
    size: '1,7m'
  },
  {
    name: 'beedrill',
    img: 'Beedrill.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'blastoise',
    img: 'Blastoise.png',
    element: 'water',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'bulbasaur',
    img: 'Bulbasaur.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'butterfree',
    img: 'Butterfree.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'caterpie',
    img: 'Caterpie.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'charizard',
    img: 'Charizard.png',
    element: 'fire',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'charmander',
    img: 'Charmander.png',
    element: 'fire',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'charmeleon',
    img: 'Charmeleon.png',
    element: 'fire',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'clefable',
    img: 'Clefable.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'dewgong',
    img: 'Dewgong.png',
    element: 'water',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'farfetchd',
    img: 'Farfetchd.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'golbat',
    img: 'Golbat.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'ivysaur',
    img: 'Ivysaur.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'kadabra',
    img: 'Kadabra.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'kakuna',
    img: 'Kakuna.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'metapod',
    img: 'Metapod.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'pidgeot',
    img: 'Pidgeot.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'pidgeotto',
    img: 'Pidgeotto.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'pidgey',
    img: 'Pidgey.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'pikachu',
    img: 'Pikachu.png',
    element: 'eletrick',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'ponyta',
    img: 'Ponyta.png',
    element: 'fire',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'raichu',
    img: 'Raichu.png',
    element: 'eletrick',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'raticate',
    img: 'Raticate.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'rattata',
    img: 'Rattata.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'squirtle',
    img: 'Squirtle.png',
    element: 'water',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'venusaur',
    img: 'Venusaur.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'vulpix',
    img: 'Vulpix.png',
    element: 'wind',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'wartortle',
    img: 'Wartortle.png',
    element: 'water',
    weigth: '2kg',
    size: '60cm',
  },
  {
    name: 'weedle',
    img: 'Weedle.png',
    element: 'grama',
    weigth: '2kg',
    size: '60cm',
  }
]

export default pokemonList